version: "3.10"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017
    restart: always
    volumes:
    - ./volume/mongodb:/data/db
    extra_hosts:
    - "host.docker.internal:host-gateway"
    stdin_open: true # docker run -i
    tty: true # docker run -t